version: "3.1"
services:
  web:
    image: obelhomme_dev:elixir
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PWD}:/workspace
    user: "${UID}:${GID}"
    working_dir: /workspace
    init: true
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=:0
